kind: pipeline
type: docker
name: chest

steps:
- name: build
  image: python:latest
  commands:
  - pip3 install -r requirements.txt
- name: deploy
  image: docker:dind
  commands:
  - pwd
  - docker ps



volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock